# Generated by Django 4.2.16 on 2024-10-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
