# Generated by Django 4.2.16 on 2024-11-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_logintable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
                ('price', models.FloatField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Submit',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='companyname',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='number',
            new_name='mobno',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='password',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='complaint',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='contactnumber',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='email',
            new_name='kbhavan',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='farmername',
            new_name='mobno',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='description',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='userid',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='description',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='policyname',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='requestproduct',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='requestproduct',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requestproduct',
            name='userid',
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='product',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='quantity',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestproduct',
            name='user',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
